pyexpander: if file position not found, return useful error anyway
instead of
pyhttpd/pyexpander.py", line 1838, in __init__
    self.posmsg("file \"%s\" not found in" % filename)
ValueError: unknown position

print
pyhttpd/pyexpander.py", line 1839, in __init__
    self.posmsg("file \"%s\" not found in" % filename)
ValueError: file "../../macros.pyex" not found in file "foo.html"